apiVersion: v1
kind: Secret
data:
  JWT_SECRET: "Yi8mJjdiNzhCRiZmdi9WZA=="
  MONGODB_PASSWORD: "TU9OR09EQl9QQVNTV09SRA=="
  PRIVATE_KEY_PASSPHRASE: "YTdkc2Y3OHNhZGc4N2FkODdzZmFnc2FkZzc4"
  MAPBOX_TOKEN: "cGsuZXlKMUlqb2lhSFZ0WVc0dFkyOXVibVZqZEdsdmJpSXNJbUVpT2lKamFqbDBjbkJ1Ykdvd2VUVmxNM1Z3WjJsek5UTnVkM1p0SW4wLktaOEtLOWw3MG9talhiRWtrYkhHc1EK"
  SMTP_USERNAME: "cmVkc29sLmludGVybmF0aW9uYWxAZ21haWwuY29tCg=="
  SMTP_PASSWORD: "SnVzdGljaWE1Lgo="
  NEO4J_USERNAME: "YWRtaW4K"
  NEO4J_PASSWORD: "YWRtaW4xMjNwYXNzCg=="
metadata:
  name: human-connection
  namespace: {{ include "hc.namespace" . }}
