---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: redsol-kv
  namespace: human-connection
spec:
  provider: azure
  secretObjects:
    - secretName: app.jwtsecret
      type: Opaque
      labels:
        environment: redsol-prod
      data:
      - objectName: JwtSecret
        key: JWT_SECRET
    - secretName: app.privatekeypassphrase
      type: Opaque
      labels:
        environment: redsol-prod
      data:
      - objectName: PrivateKeyPassphrase
        key: PRIVATE_KEY_PASSPHRASE
    - secretName: app.neo4j.username
      type: Opaque
      labels:
        environment: redsol-prod
      data:
      - objectName: Neo4jUsername
        key: NEO4J_USERNAME
    - secretName: app.neo4j.password
      type: Opaque
      labels:
        environment: redsol-prod
      data:
      - objectName: Neo4jPassword
        key: NEO4J_PASSWORD
    - secretName: app.mapboxtoken
      type: Opaque
      labels:
        environment: redsol-prod
      data:
      - objectName: MapBoxToken
        key: MAPBOX_TOKEN
    - secretName: app.smtp.username
      type: Opaque
      labels:
        environment: redsol-prod
      data:
      - objectName: SmtpUsername
        key: SMTP_USERNAME
    - secretName: app.smtp.password
      type: Opaque
      labels:
        environment: redsol-prod
      data:
      - objectName: SmtpPassword
        key: SMTP_PASSWORD
  parameters:
    cloudName: "AZUREPUBLICCLOUD"
    tenantId: "bd30d232-523c-4db9-9683-2b808f56c3aa"
    keyvaultName: "redsol-kv"
    usePodIdentity: "true"
    objects: |
      array:
      - |
        objectName: JwtSecret
        objectType: secret
        objectAlias: JwtSecret
      - |
        objectName: PrivateKeyPassphrase
        objectType: secret
        objectAlias: PrivateKeyPassphrase
      - |
        objectName: Neo4jUsername
        objectType: secret
        objectAlias: Neo4jUsername
      - |
        objectName: Neo4jPassword
        objectType: secret
        objectAlias: Neo4jPassword
      - |
        objectName: MapBoxToken
        objectType: secret
        objectAlias: MapBoxToken
      - |
        objectName: SmtpUsername
        objectType: secret
        objectAlias: SmtpUsername
      - |
        objectName: SmtpPassword
        objectType: secret
        objectAlias: SmtpPassword

---
apiVersion: v1
kind: Secret
data:
  MONGODB_PASSWORD: "TU9OR09EQl9QQVNTV09SRA=="
metadata:
  name: human-connection
  namespace: {{ include "hc.namespace" . }}
