---
# https://docs.microsoft.com/en-us/azure/application-gateway/ingress-controller-expose-service-over-http-https
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-app-ingress
  namespace: demo-app
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      # - path: /demo-app(/|$)(.*)
      - path: /
        pathType: Exact
        backend:
          service:
            name: demo-app
            port:
              number: 80
      # - path: /(.*)
      # - path: /
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: demo-app
      #       port:
      #         number: 80