# https://github.com/github/kube/blob/master/docs/kubernetes/resources/service.md
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app
  namespace: demo-app
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 80
  selector:
    app: demo-app