apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-claim
  namespace: {{ include "hc.namespace" . }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 5Gi