---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: human-connection-ingress
  namespace: {{ include "hc.namespace" . }}
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: {{ include "hc.backend.url" .}}/
        pathType: Exact
        backend:
          service:
            name: backend
            port:
              number: 80