# https://github.com/github/kube/blob/master/docs/kubernetes/resources/service.md
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ include "hc.namespace" . }}
  labels:
    app: backend
spec:
  type: ClusterIP
  ports:
    # name: backend
    - protocol: TCP
      targetPort: 4000
      port: 4000
  selector:
    app: backend
