---
apiVersion: v1
kind: ConfigMap
data:
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "465"
  SMTP_IGNORE_TLS: "true"
  SMTP_USERNAME: "redsol.international@gmail.com"
  SMTP_PASSWORD: "Justicia5."
  GRAPHQL_URI: "http://neo4j.human-connection-dev.svc.cluster.local:4000"
  NEO4J_URI: "bolt://neo4j.human-connection-dev.svc.cluster.local:7687"
  NEO4J_AUTH: "none"
  NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
  CLIENT_URI: "http://backend.human-connection-dev.svc.cluster.local:3000"
  NEO4J_apoc_import_file_enabled: "true"
  NEO4J_dbms_memory_pagecache_size: "768M"
  NEO4J_dbms_memory_heap_max__size: "1024M"
  NEO4J_dbms_memory_heap_initial__size: "500M"
  NEO4J_dbms_security_procedures_unrestricted: "algo.*,apoc.*"
  SENTRY_DSN_WEBAPP: ""
  SENTRY_DSN_BACKEND: ""
  COMMIT: ""
metadata:
  name: configmap
  namespace: {{ include "hc.namespace" . }}
