#
# we're building docker images from JusticeInternational/Human-Connection/docker-compose.yml config
# this is where we can get images ready for publishing.
#
name: Build Docker Images

on:
  push:
    branches:
      - master
      - update-ref

env:
  # built from https://github.com/JusticeInternational/project-config/packages/290557?version=latest
  DB_IMAGE: db
  ACR_REGISTRY_URL: redsol.azurecr.io
  IMAGE_REGISTRY_URL: docker.pkg.github.com
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Get Docker Repo Name
        id: get-repository
        run: |
          echo "::set-output name=docker-repo::$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]' )"

      - name: Clone JusticeInternational/Human-Connection
        run: |
          git clone https://github.com/JusticeInternational/Human-Connection

      - name: Build db image
        run: |
          cd Human-Connection
          docker-compose build neo4j
          docker tag humanconnection/neo4j:latest ${{ env.IMAGE_REGISTRY_URL }}/${{ steps.get-repository.outputs.docker-repo }}/${{ env.DB_IMAGE }}:latest
          docker tag humanconnection/neo4j:latest ${{ env.ACR_REGISTRY_URL }}/${{ steps.get-repository.outputs.docker-repo }}/${{ env.DB_IMAGE }}:latest

#
# TODO we need an if case statement that only pushes when this merges to the default branch
      - name: Save db image
        run: |
          echo ${{ env.GITHUB_TOKEN }} | docker login ${{ env.IMAGE_REGISTRY_URL }} --password-stdin --username ${{ github.actor }} && \
          echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ env.ACR_REGISTRY_URL }} --password-stdin --username ${{ secrets.ACR_USERNAME }}  && \
          docker push ${{ env.IMAGE_REGISTRY_URL}}/${{ steps.get-repository.outputs.docker-repo }}/${{ env.DB_IMAGE }}:latest
          docker push ${{ env.ACR_REGISTRY_URL}}/${{ steps.get-repository.outputs.docker-repo }}/${{ env.DB_IMAGE }}:latest
